/**
 * PDF Export Utility
 * Generates professional PDF documents from Markdown content
 * Requires: jspdf (npm install jspdf)
 */

/**
 * Converts Markdown text to plain text (removes markdown syntax)
 * Simple implementation - handles common markdown patterns
 */
function markdownToPlainText(markdown) {
  if (!markdown) return '';
  
  return markdown
    // Remove headers
    .replace(/^#{1,6}\s+(.+)$/gm, '$1')
    // Remove bold/italic
    .replace(/\*\*(.+?)\*\*/g, '$1')
    .replace(/\*(.+?)\*/g, '$1')
    // Remove links but keep text
    .replace(/\[([^\]]+)\]\([^\)]+\)/g, '$1')
    // Remove code blocks
    .replace(/```[\s\S]*?```/g, '')
    .replace(/`([^`]+)`/g, '$1')
    // Remove list markers but keep content
    .replace(/^[\s]*[-*+]\s+/gm, '• ')
    .replace(/^[\s]*\d+\.\s+/gm, '')
    // Clean up extra whitespace
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

/**
 * Wraps text to fit within page width
 */
function wrapText(doc, text, x, y, maxWidth, lineHeight) {
  const words = text.split(' ');
  let line = '';
  let currentY = y;
  
  for (let i = 0; i < words.length; i++) {
    const testLine = line + words[i] + ' ';
    const testWidth = doc.getTextWidth(testLine);
    
    if (testWidth > maxWidth && i > 0) {
      doc.text(line, x, currentY);
      line = words[i] + ' ';
      currentY += lineHeight;
    } else {
      line = testLine;
    }
  }
  
  doc.text(line, x, currentY);
  return currentY + lineHeight;
}

/**
 * Generates a PDF document from Markdown content
 * @param {string} title - Document title (e.g., "Behavior Intervention Plan")
 * @param {string} content - Markdown-formatted content
 * @param {string} schoolName - School name for header
 * @param {string} appName - App name for footer (default: "PrismPath")
 */
export async function generatePDF(title, content, schoolName = '', appName = 'PrismPath') {
  // Dynamic import to avoid build-time errors if jspdf isn't installed
  let jsPDF;
  try {
    jsPDF = (await import('jspdf')).default;
  } catch (error) {
    throw new Error('jsPDF is not installed. Please run: npm install jspdf');
  }

  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  const margin = 20;
  const maxWidth = pageWidth - (margin * 2);
  let currentY = margin;
  const lineHeight = 7;
  const headerHeight = 30;
  const footerHeight = 20;

  // Set font
  doc.setFont('helvetica'); // Arial-like, widely supported
  doc.setFontSize(10);

  // Header
  if (schoolName) {
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`${schoolName} - Official Document`, margin, currentY);
    currentY += 10;
  }

  // Title
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  const titleLines = doc.splitTextToSize(title, maxWidth);
  doc.text(titleLines, margin, currentY);
  currentY += (titleLines.length * lineHeight) + 10;

  // Content
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  
  // Convert markdown to plain text and split into paragraphs
  const plainText = markdownToPlainText(content);
  const paragraphs = plainText.split(/\n\n+/).filter(p => p.trim());
  
  for (const paragraph of paragraphs) {
    // Check if we need a new page
    if (currentY + lineHeight * 3 > pageHeight - footerHeight) {
      doc.addPage();
      currentY = margin;
    }
    
    // Handle bullet points
    if (paragraph.trim().startsWith('•')) {
      const bulletText = paragraph.replace(/^•\s*/, '');
      doc.text('•', margin, currentY);
      const wrappedLines = doc.splitTextToSize(bulletText, maxWidth - 10);
      doc.text(wrappedLines, margin + 5, currentY);
      currentY += wrappedLines.length * lineHeight + 3;
    } else {
      // Regular paragraph
      const wrappedLines = doc.splitTextToSize(paragraph, maxWidth);
      doc.text(wrappedLines, margin, currentY);
      currentY += wrappedLines.length * lineHeight + 5;
    }
  }

  // Footer on each page
  const totalPages = doc.internal.pages.length - 1;
  for (let i = 1; i <= totalPages; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    const footerText = `Generated by ${appName} on ${new Date().toLocaleDateString()}`;
    doc.text(footerText, margin, pageHeight - 10, { align: 'left' });
    doc.text(`Page ${i} of ${totalPages}`, pageWidth - margin, pageHeight - 10, { align: 'right' });
  }

  // Generate filename
  const sanitizedTitle = title.replace(/[^a-z0-9]/gi, '_').toLowerCase();
  const filename = `${sanitizedTitle}_${new Date().toISOString().split('T')[0]}.pdf`;

  // Download
  doc.save(filename);
}

